# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CeliaGui(object):
    def setupUi(self, CeliaGui):
        CeliaGui.setObjectName("CeliaGui")
        CeliaGui.resize(938, 610)
        self.centralwidget = QtWidgets.QWidget(CeliaGui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 931, 611))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/jarvis.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(700, 520, 75, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(780, 520, 75, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 381, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("img/loader.gif"))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(490, 50, 201, 31))
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(710, 50, 201, 31))
        self.textBrowser_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        CeliaGui.setCentralWidget(self.centralwidget)

        self.retranslateUi(CeliaGui)
        QtCore.QMetaObject.connectSlotsByName(CeliaGui)

    def retranslateUi(self, CeliaGui):
        _translate = QtCore.QCoreApplication.translate
        CeliaGui.setWindowTitle(_translate("CeliaGui", "MainWindow"))
        self.pushButton.setText(_translate("CeliaGui", "Run"))
        self.pushButton_2.setText(_translate("CeliaGui", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CeliaGui = QtWidgets.QMainWindow()
    ui = Ui_CeliaGui()
    ui.setupUi(CeliaGui)
    CeliaGui.show()
    sys.exit(app.exec_())
